### ISSUE TITLE
运行时出现错误，请教这是怎么回事

### ISSUE THREAD

**Issue by snowlixue** [thunlp/attribute_charge#10]
Traceback (most recent call last):
  File "train.py", line 368, in <module>
    tf.app.run()
  File "/home/lx/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 83, in main
    lstm_model = model.LSTM_MODEL(word_embeddings=word_embeddings,attr_table=attr_table,config = lstm_config)
  File "/home/lx/attribute_charge-master/code/model.py", line 50, in __init__
    self.attn_weights = tf.concat(1, [tf.expand_dims(temp,1) for temp in self.attention_weights])
  File "/home/lx/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1122, in concat
    tensor_shape.scalar())
  File "/home/lx/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 848, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (10, 32, 1, 500) and () are incompatible

**Comment by snowlixue** [comment]
tensorflow版本问题，已解决
